[[data]]
even_week = true
day = "Среда"

[[data.schedule]]
lesson = "Информатика (Лек)"
type = "Лекция"
cohort = "ИНФОРМ 1"
teacher.name = "Балакшин Павел Валерьевич"
teacher.id = 125598
time.start_time = "11:30"
time.end_time = "13:00"
location.address = "ул.Ломоносова, д.9, лит. М"
location.auditory = "ауд. Актовый зал (1216/0 (усл))"
format = "Очно - дистанционный"
weeks = [2, 4, 6, 8, 10, 12, 14, 16]

[[data.schedule]]
lesson = "Основы профессиональной деятельности (Лек)"
type = "Лекция"
cohort = "ОПД 1"
teacher.name = "Клименков Сергей Викторович"
teacher.id = 105395
time.start_time = "13:30"
time.end_time = "15:00"
location.address = "ул.Ломоносова, д.9, лит. М"
location.auditory = "ауд. Актовый зал (1216/0 (усл))"
format = "Очно - дистанционный"
weeks = [2, 4, 6, 8, 10, 12, 14, 16]

[[data.schedule]]
lesson = "English A2 / Английский язык А2 (Прак)"
type = "Практика"
cohort = "22"
teacher.name = "Коваленко Наталья Игоревна"
teacher.id = 426629
time.start_time = "15:30"
time.end_time = "17:00"
location.address = "ул.Ломоносова, д.9, лит. Е"
location.auditory = "ауд. 3225"
format = "Очно - дистанционный"
weeks = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

[[data.schedule]]
lesson = "English A2 / Английский язык А2 (Прак)"
type = "Практика"
cohort = "22"
teacher.name = "Коваленко Наталья Игоревна"
teacher.id = 426629
time.start_time = "17:10"
time.end_time = "18:40"
location.address = "ул.Ломоносова, д.9, лит. Е"
location.auditory = "ауд. 3225"
format = "Очно - дистанционный"
weeks = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

[[data]]
even_week = true
day = "Суббота"

[[data.schedule]]
lesson = "Информатика (Лаб)"
type = "Лабораторная"
cohort = "ИНФОРМ (Р3106) 1.1"
teacher.name = "Балакшин Павел Валерьевич"
teacher.id = 125598
time.start_time = "11:30"
time.end_time = "13:00"
location.address = "Кронверкский пр., д.49, лит.А"
location.auditory = "ауд. 1333"
format = "Очно - дистанционный"
weeks = [2, 4, 6, 8, 10, 12, 14, 16]

[[data.schedule]]
lesson = "Информатика (Лаб)"
type = "Лабораторная"
cohort = "ИНФОРМ (Р3106) 1.1"
teacher.name = "Балакшин Павел Валерьевич"
teacher.id = 125598
time.start_time = "13:30"
time.end_time = "15:00"
location.address = "Кронверкский пр., д.49, лит.А"
location.auditory = "ауд. 1333"
format = "Очно - дистанционный"
weeks = [2, 4, 6, 8, 10, 12, 14, 16]